<?php
require_once __DIR__ . '/p360-db.php';
require_once __DIR__ . '/p360-auth.php';
require_once __DIR__ . '/p360-csrf.php';
require_once __DIR__ . '/p360-validation.php';
require_once __DIR__ . '/p360-money.php';
require_once __DIR__ . '/p360-date.php';
require_once __DIR__ . '/p360-jalali.php';
require_once __DIR__ . '/p360-search.php';
require_once __DIR__ . '/p360-audit.php';
require_once __DIR__ . '/p360-workflow.php';
require_once __DIR__ . '/p360-rules-engine.php';
require_once __DIR__ . '/p360-legal-rules.php';
require_once __DIR__ . '/p360-contract-template-engine.php';
require_once __DIR__ . '/p360-attendance-engine.php';
require_once __DIR__ . '/p360-payroll-engine.php';
require_once __DIR__ . '/p360-company-repository.php';
require_once __DIR__ . '/p360-employee-repository.php';
require_once __DIR__ . '/p360-recruitment-repository.php';
require_once __DIR__ . '/p360-service-repository.php';
require_once __DIR__ . '/p360-loan-repository.php';
require_once __DIR__ . '/p360-performance-repository.php';
require_once __DIR__ . '/p360-equipment-repository.php';
require_once __DIR__ . '/p360-report-repository.php';
require_once __DIR__ . '/p360-document-repository.php';
require_once __DIR__ . '/p360-ui.php';
require_once __DIR__ . '/p360-aliases.php';
p360_session_start();