/* Rollback INV360_003 — drops only inv360_* tables. No ERP tables touched. */
SET NOCOUNT ON; SET XACT_ABORT ON;
IF DB_NAME() <> N'moghare360_ERP' THROW 57002, 'INV360_003 rollback must run on moghare360_ERP only.', 1;
BEGIN TRY BEGIN TRANSACTION;
DECLARE @t NVARCHAR(128), @sql NVARCHAR(400);
DECLARE c CURSOR FOR SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME LIKE 'inv360_%' ORDER BY TABLE_NAME DESC;
OPEN c; FETCH NEXT FROM c INTO @t;
WHILE @@FETCH_STATUS=0 BEGIN SET @sql=N'DROP TABLE dbo.'+QUOTENAME(@t); EXEC(@sql); FETCH NEXT FROM c INTO @t; END;
CLOSE c; DEALLOCATE c;
COMMIT TRANSACTION; END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK TRANSACTION; THROW; END CATCH;